#Requires -Version 5.1
<#
.SYNOPSIS
    Scaffolds a new Node.js Express API project.
.DESCRIPTION
    This script initializes a new project directory for a Node.js API using Express.
    It performs the following actions:
    - Initializes a Git repository.
    - Runs 'npm init -y'.
    - Installs 'express' and 'dotenv' as dependencies.
    - Creates a 'src' directory with a minimal 'server.js'.
    - Creates a .env file.
    - Creates a .gitignore file for Node.js projects.
.NOTES
    Author: Gemini
    Date: 2025-11-11
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param()

begin {
    $OriginalErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Stop'

    function Wait-Path {
        param(
            [string]$Path,
            [int]$MaxRetries = 50,
            [int]$RetryIntervalMs = 100
        )
        $retryCount = 0
        while (-not (Test-Path -Path $Path) -and $retryCount -lt $MaxRetries) {
            Start-Sleep -Milliseconds $RetryIntervalMs
            $retryCount++
        }
        if (-not (Test-Path -Path $Path)) {
            throw "Failed to find path '$Path' after $MaxRetries retries."
        }
    }

    $GitignoreContent = @'
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-temporary-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache files
.cache
dist/

# Next.js build output
.next
out/

# Nuxt.js build output
.nuxt
dist/

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port
'@

    $ServerJsContent = @"
const express = require('express');
require('dotenv').config();

const app = express();
const port = process.env.PORT || 3000;

app.get('/', (req, res) => {
    res.send('Hello World!');
});

app.listen(port, () => {
    console.log(`Server is running on http://localhost:${port}`);
});
"@
}

process {
    try {
        # Git Initialization
        if (-not (Test-Path -Path '.git')) {
            if ($PSCmdlet.ShouldProcess('current directory', 'Initialize Git repository')) {
                Write-Host "Initializing Git repository..."
                git init | Out-Null
            }
        }
        else {
            Write-Warning "Git repository already exists in this directory."
        }

        # npm init
        if (-not (Test-Path -Path 'package.json')) {
            if ($PSCmdlet.ShouldProcess('current directory', 'Run npm init -y')) {
                Write-Host "Running 'npm init -y'..."
                npm init -y | Out-Null
            }
        }
        else {
            Write-Warning "'package.json' already exists."
        }

        # Install dependencies
        if ($PSCmdlet.ShouldProcess('express, dotenv', 'Install npm packages')) {
            Write-Host "Installing npm packages: express, dotenv..."
            npm install express dotenv | Out-Null
        }

        # Create src directory
        if (-not (Test-Path -Path 'src')) {
            if ($PSCmdlet.ShouldProcess('src', 'Create directory')) {
                Write-Host "Creating directory: src"
                New-Item -ItemType Directory -Path 'src' | Out-Null
                Wait-Path -Path 'src'
            }
        }

        # Create server.js
        if ($PSCmdlet.ShouldProcess('src/server.js', 'Create file with content')) {
            Write-Host "Creating file: src/server.js"
            Set-Content -Path 'src/server.js' -Value $ServerJsContent
        }

        # Create .env file
        if (-not (Test-Path -Path '.env')) {
            if ($PSCmdlet.ShouldProcess('.env', 'Create empty file')) {
                Write-Host "Creating file: .env"
                Set-Content -Path '.env' -Value "PORT=3000"
            }
        }

        # Create .gitignore
        if (-not (Test-Path -Path '.gitignore')) {
            if ($PSCmdlet.ShouldProcess('.gitignore', 'Create file with content')) {
                Write-Host "Creating .gitignore"
                Set-Content -Path '.gitignore' -Value $GitignoreContent
            }
        }

        Write-Host "`nNode.js API project scaffolded successfully."
        Write-Host "Run 'node src/server.js' to start the server."

    }
    catch {
        Write-Error "An error occurred during project scaffolding: $_"
        exit 1
    }
    finally {
        $ErrorActionPreference = $OriginalErrorActionPreference
    }
}

